# Generated by Django 4.2.3 on 2023-07-22 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workspaces.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='software/images', validators=[workspaces.validators.validate_file_size])),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='workspaces_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
