# Generated by Django 4.2.3 on 2023-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_remove_workspaces_users_workspacesusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesusers',
            name='user',
        ),
        migrations.AddField(
            model_name='workspacesusers',
            name='active',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspacesusers',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
