# Generated by Django 4.2.3 on 2023-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_remove_workspacesusers_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacesusers',
            old_name='Workspace',
            new_name='workspace',
        ),
    ]
