# Generated by Django 4.2.3 on 2023-07-23 08:41

from django.db import migrations, models
import workspaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_rename_workspace_workspacesusers_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='software/images', validators=[workspaces.validators.validate_file_size]),
        ),
    ]
