# Generated by Django 4.2.3 on 2023-07-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_softwareadmin',
        ),
    ]
