# Generated by Django 4.2.3 on 2023-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_softwareadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wsadmin',
            field=models.BooleanField(default=False),
        ),
    ]
